name: clang-format-review

# You can be more specific, but it currently only works on pull requests
on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
      - name: Analyze
        run: |
          clang-format --dry-run --Werror -style=file $(find ./ -name '*.cpp' -print)
          clang-format --dry-run --Werror -style=file $(find ./ -name '*.h' -print)
